#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# reload the configuration to apply new configuration
if systemctl --user -q is-active prometheus.service; then
    systemctl --user restart prometheus.service
fi
