#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# reload the configuration to apply new configuration
systemctl --user restart prometheus.service alertmanager.service alert-proxy.service

if [ -n "$GRAFANA_PATH" ]; then
    systemctl --user enable grafana.service
    systemctl --user restart grafana.service
else
    systemctl --user disable grafana.service
    systemctl --user stop grafana.service
fi
