#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# reload the subscription configuration
write-alert-proxy-envfile
systemctl --user restart alert-proxy.service
