#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# reload the subscription configuration
if systemctl --user -q is-active alert-proxy.service; then
    systemctl --user restart alert-proxy.service
fi