#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# reload the smarthost configuration
reload_configuration
systemctl --user try-restart alertmanager.service
