#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent
import agent.tasks

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Remove traefik routes
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='delete-route',
    data={
        'instance': os.environ['MODULE_ID'] + '_prometheus'
    },
)
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='delete-route',
    data={
        'instance': os.environ['MODULE_ID'] + '_grafana'
    },
)
