#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

rdb = agent.redis_connect(use_replica=True)

# Read config from Redis
if rdb.exists(f'module/{os.environ["MODULE_ID"]}/settings'):
    config = rdb.hgetall(f'module/{os.environ["MODULE_ID"]}/settings')
else:
    config = {"prometheus_path": None, "grafana_path": None,  "mail_to": [], "mail_from": None, "mail_template": None}

json.dump(config, fp=sys.stdout)
