#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

# Read config.json if exists
if os.path.exists('config.json'):
    with open('config.json', 'r') as f:
        config = json.load(f)
else:
    config = {"prometheus_path": None, "grafana_path": None, "lets_encrypt": False, "mail_to": [], "mail_from": None}

json.dump(config, fp=sys.stdout)
